"""Service layer: business logic shared by the API and the Celery workers."""

from app.services.errors import (
    AuthenticationError,
    InactiveUserError,
    JobAlreadyExistsError,
    JobNotFoundError,
    ServiceError,
    UserAlreadyExistsError,
    UserNotFoundError,
)
from app.services.embedding_service import (
    backfill_embeddings,
    build_job_text,
    build_search_text,
    generate_embeddings_batch,
    generate_job_embedding,
    generate_search_embedding,
    get_jobs_without_embeddings,
    update_job_embedding,
)
from app.services.candidate_kb_service import (
    CandidateKBNotFoundError,
    CandidateKBValidationError,
    delete_candidate_kb,
    filter_restricted_references,
    get_active_kb_record,
    kb_to_public_dict,
    list_candidate_kb_versions,
    load_candidate_kb,
    load_candidate_kb_optional,
    save_candidate_kb,
    save_candidate_kb_from_dict,
    validate_kb_dict,
)
from app.services.evaluation_service import (
    evaluate_job_for_user,
    evaluate_job_with_kb,
    get_candidate_kb,
)
from app.services.ats_service import analyze_ats, extract_job_keywords
from app.services.resume_service import build_tailored_resume
from app.services.cover_letter_service import build_cover_letter
from app.services.document_service import (
    DocumentGenerationError,
    DocumentNotFoundError,
    generate_cover_letter,
    generate_resume,
    get_document,
    list_documents,
    regenerate_document,
    update_document_content,
    update_document_status,
)
from app.services.document_storage import (
    DocumentStorage,
    LocalFilesystemStorage,
    get_document_storage,
    set_document_storage,
)
from app.services.application_service import (
    ApplicationExistsError,
    ApplicationNotFoundError,
    GuardFailedError,
    InvalidTransitionError,
    create_application,
    get_application,
    get_application_for_job,
    get_or_create_application,
    is_valid_transition,
    list_applications,
    list_events,
    record_event,
    record_submission_failure,
    transition_application,
)
from app.services.browser_automation_service import (
    SubmissionBlockedError,
    SubmitOutcome,
    build_applicant_data,
    submit_application,
)
from app.services.job_discovery_service import (
    bulk_upsert_jobs,
    count_jobs as count_discovery_jobs,
    create_job_from_discovery,
    get_job_by_id as get_discovery_job_by_id,
    get_job_by_source_id,
    get_job_by_url as get_discovery_job_by_url,
    get_job_or_raise as get_discovery_job_or_raise,
    list_jobs as list_discovery_jobs,
)
from app.services.job_service import (
    count_jobs,
    create_job,
    get_job_by_id,
    get_job_by_url,
    get_job_or_raise,
    list_jobs,
)
from app.services.semantic_search_service import (
    create_hnsw_index,
    create_ivfflat_index,
    get_similar_jobs,
    hybrid_search_jobs,
    semantic_search_jobs,
)
from app.services.user_service import (
    authenticate_user,
    create_user,
    get_user_by_email,
    get_user_by_id,
    update_user,
)

__all__ = [
    "ApplicationExistsError",
    "ApplicationNotFoundError",
    "AuthenticationError",
    "CandidateKBNotFoundError",
    "CandidateKBValidationError",
    "DocumentGenerationError",
    "DocumentNotFoundError",
    "DocumentStorage",
    "GuardFailedError",
    "InactiveUserError",
    "InvalidTransitionError",
    "JobAlreadyExistsError",
    "JobNotFoundError",
    "LocalFilesystemStorage",
    "ServiceError",
    "SubmissionBlockedError",
    "SubmitOutcome",
    "UserAlreadyExistsError",
    "UserNotFoundError",
    "analyze_ats",
    "authenticate_user",
    "backfill_embeddings",
    "build_applicant_data",
    "build_cover_letter",
    "build_job_text",
    "build_search_text",
    "build_tailored_resume",
    "bulk_upsert_jobs",
    "count_discovery_jobs",
    "count_jobs",
    "create_application",
    "create_hnsw_index",
    "create_ivfflat_index",
    "create_job",
    "create_job_from_discovery",
    "create_user",
    "delete_candidate_kb",
    "evaluate_job_for_user",
    "evaluate_job_with_kb",
    "extract_job_keywords",
    "filter_restricted_references",
    "generate_cover_letter",
    "generate_embeddings_batch",
    "generate_job_embedding",
    "generate_resume",
    "generate_search_embedding",
    "get_active_kb_record",
    "get_application",
    "get_application_for_job",
    "get_candidate_kb",
    "get_discovery_job_by_id",
    "get_discovery_job_by_url",
    "get_discovery_job_or_raise",
    "get_document",
    "get_document_storage",
    "get_job_by_id",
    "get_job_by_source_id",
    "get_job_by_url",
    "get_job_or_raise",
    "get_jobs_without_embeddings",
    "get_or_create_application",
    "get_similar_jobs",
    "get_user_by_email",
    "get_user_by_id",
    "hybrid_search_jobs",
    "is_valid_transition",
    "kb_to_public_dict",
    "list_applications",
    "list_candidate_kb_versions",
    "list_discovery_jobs",
    "list_documents",
    "list_events",
    "list_jobs",
    "load_candidate_kb",
    "load_candidate_kb_optional",
    "record_event",
    "record_submission_failure",
    "regenerate_document",
    "save_candidate_kb",
    "save_candidate_kb_from_dict",
    "semantic_search_jobs",
    "set_document_storage",
    "submit_application",
    "transition_application",
    "update_document_content",
    "update_document_status",
    "update_job_embedding",
    "update_user",
    "validate_kb_dict",
]
