"""Service layer: business logic shared by the API and the Celery workers."""

from app.services.errors import (
    AuthenticationError,
    InactiveUserError,
    JobAlreadyExistsError,
    JobNotFoundError,
    ServiceError,
    UserAlreadyExistsError,
    UserNotFoundError,
)
from app.services.embedding_service import (
    backfill_embeddings,
    build_job_text,
    build_search_text,
    generate_embeddings_batch,
    generate_job_embedding,
    generate_search_embedding,
    get_jobs_without_embeddings,
    update_job_embedding,
)
from app.services.candidate_kb_service import (
    CandidateKBNotFoundError,
    CandidateKBValidationError,
    delete_candidate_kb,
    filter_restricted_references,
    get_active_kb_record,
    kb_to_public_dict,
    list_candidate_kb_versions,
    load_candidate_kb,
    load_candidate_kb_optional,
    save_candidate_kb,
    save_candidate_kb_from_dict,
    validate_kb_dict,
)
from app.services.evaluation_service import (
    evaluate_job_for_user,
    evaluate_job_with_kb,
    get_candidate_kb,
)
from app.services.job_discovery_service import (
    bulk_upsert_jobs,
    count_jobs as count_discovery_jobs,
    create_job_from_discovery,
    get_job_by_id as get_discovery_job_by_id,
    get_job_by_source_id,
    get_job_by_url as get_discovery_job_by_url,
    get_job_or_raise as get_discovery_job_or_raise,
    list_jobs as list_discovery_jobs,
)
from app.services.job_service import (
    count_jobs,
    create_job,
    get_job_by_id,
    get_job_by_url,
    get_job_or_raise,
    list_jobs,
)
from app.services.semantic_search_service import (
    create_hnsw_index,
    create_ivfflat_index,
    get_similar_jobs,
    hybrid_search_jobs,
    semantic_search_jobs,
)
from app.services.user_service import (
    authenticate_user,
    create_user,
    get_user_by_email,
    get_user_by_id,
    update_user,
)

__all__ = [
    "AuthenticationError",
    "CandidateKBNotFoundError",
    "CandidateKBValidationError",
    "InactiveUserError",
    "JobAlreadyExistsError",
    "JobNotFoundError",
    "ServiceError",
    "UserAlreadyExistsError",
    "UserNotFoundError",
    "authenticate_user",
    "backfill_embeddings",
    "build_job_text",
    "build_search_text",
    "bulk_upsert_jobs",
    "count_discovery_jobs",
    "count_jobs",
    "create_hnsw_index",
    "create_ivfflat_index",
    "create_job",
    "create_job_from_discovery",
    "create_user",
    "delete_candidate_kb",
    "evaluate_job_for_user",
    "evaluate_job_with_kb",
    "filter_restricted_references",
    "generate_embeddings_batch",
    "generate_job_embedding",
    "generate_search_embedding",
    "get_active_kb_record",
    "get_candidate_kb",
    "get_discovery_job_by_id",
    "get_discovery_job_by_url",
    "get_discovery_job_or_raise",
    "get_job_by_id",
    "get_job_by_source_id",
    "get_job_by_url",
    "get_job_or_raise",
    "get_jobs_without_embeddings",
    "get_similar_jobs",
    "get_user_by_email",
    "get_user_by_id",
    "hybrid_search_jobs",
    "kb_to_public_dict",
    "list_candidate_kb_versions",
    "list_discovery_jobs",
    "list_jobs",
    "load_candidate_kb",
    "load_candidate_kb_optional",
    "save_candidate_kb",
    "save_candidate_kb_from_dict",
    "semantic_search_jobs",
    "update_job_embedding",
    "update_user",
    "validate_kb_dict",
]
